language: cpp

sudo: false

before_script:
  - eval "${MATRIX_EVAL}"
  - echo ${CXX}
  - ${CXX} --version
  - echo "CC=$CXX" > make/local

linux_clang: &linux_clang
  os: linux
  compiler: "clang-3.8"
  addons:
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
      packages: [ 'clang-3.8', 'libc++-dev' ]

linux_gcc: &linux_gcc
  os: linux
  compiler: "gcc-4.9"
  addons:
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.9' ]

before_install: make math-revert

matrix:
  fast_finish: true
  include:
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER="src/test/unit/callbacks src/test/unit/io"
          PARALLEL=2
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER=src/test/unit/lang
          PARALLEL=2
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER="src/test/unit/mcmc src/test/unit/model src/test/unit/optimization"
          PARALLEL=2
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER="src/test/unit/services src/test/unit/variational src/test/unit/version_test.cpp"
          PARALLEL=2
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER="src/test/unit/callbacks src/test/unit/io"
          PARALLEL=2
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER=src/test/unit/lang
          PARALLEL=1
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER="src/test/unit/mcmc src/test/unit/model src/test/unit/optimization"
          PARALLEL=1
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER="src/test/unit/services src/test/unit/variational src/test/unit/version_test.cpp"
          PARALLEL=2

script: ./runTests.py -j$PARALLEL $TESTFOLDER

sudo: false
dist: trusty
